module.exports = [
  {
    "name": "Serena",
    "arcana": "Major",
    "cluster": "Serena",
    "twin": "Baby Zero",
    "spoilBook": 1,
    "generation": 0,
    "origin": null,
    "gender": "Agender",
    "pronouns": "She/Her",
    "created": null,
    "died": null,
    "age": 415,
    "sphere": "Godshi Enpire"
  },
  {
    "name": "Snuffle",
    "arcana": "Minor",
    "cluster": "Nooka",
    "twin": null,
    "spoilBook": 5,
    "generation": 0,
    "origin": null,
    "gender": "Male Cat",
    "pronouns": "He/Him",
    "created": null,
    "died": null,
    "age": 314,
    "sphere": "Evol Espireth"
  },
  {
    "name": "Baby Zero",
    "arcana": "Minor",
    "cluster": "Morgana",
    "twin": "Serena",
    "spoilBook": 5,
    "generation": 0,
    "origin": null,
    "gender": "Trans Boy",
    "pronouns": "He/Him",
    "created": 1982,
    "died": null,
    "age": 0,
    "sphere": "Geren Eshper"
  },
  {
    "name": "Clairey",
    "arcana": "Minor",
    "cluster": "Morgana",
    "twin": "Katie",
    "spoilBook": 1,
    "generation": 1,
    "origin": "Serena",
    "gender": "Cis Girl",
    "pronouns": "She/Her",
    "created": 1985,
    "died": null,
    "age": 7,
    "sphere": "Geren Eshper"
  },
  {
    "name": "Katie",
    "arcana": "Minor",
    "cluster": "Morgana",
    "twin": "Clairey",
    "spoilBook": 1,
    "generation": 1,
    "origin": "Serena",
    "gender": "Cis Girl",
    "pronouns": "She/Her",
    "created": 1985,
    "died": null,
    "age": 7,
    "sphere": "Geren Eshper"
  },
  {
    "name": "Clarence",
    "arcana": null,
    "cluster": "Ghost",
    "twin": null,
    "spoilBook": 5,
    "generation": 1,
    "origin": "Serena",
    "gender": "Dead Boy",
    "pronouns": "Was/Were",
    "created": 1987,
    "died": 1988,
    "age": null,
    "sphere": null
  },
  {
    "name": "Charles",
    "arcana": "Minor",
    "cluster": "Nooka",
    "twin": "Reckmund",
    "spoilBook": 5,
    "generation": 1,
    "origin": "Clarence",
    "gender": "Trans Man",
    "pronouns": "He/Him",
    "created": 1988,
    "died": null,
    "age": 21,
    "sphere": "Geren Espher"
  },
  {
    "name": "Reckmund",
    "arcana": "Minor",
    "cluster": "Alicia",
    "twin": "Charles",
    "spoilBook": 5,
    "generation": 1,
    "origin": "Clarence",
    "gender": "Trans Man",
    "pronouns": "He/Him",
    "created": 1988,
    "died": null,
    "age": 21,
    "sphere": "Pyro Eshwelle"
  },
  {
    "name": "Fuchsia",
    "arcana": "Minor",
    "cluster": "Honeysuckle",
    "twin": "Anxia Terra",
    "spoilBook": 1,
    "generation": 2,
    "origin": "Clairey",
    "gender": "Female",
    "pronouns": "She/her",
    "created": 1989,
    "died": null,
    "age": 14,
    "sphere": "Geren Eshper"
  },
  {
    "name": "Anxia Terra",
    "arcana": "Minor",
    "cluster": "Alicia",
    "twin": "Fuchsia",
    "spoilBook": 1,
    "generation": 2,
    "origin": "Katie",
    "gender": "Female",
    "pronouns": "She/her",
    "created": 1989,
    "died": null,
    "age": 14,
    "sphere": "Geren Eshper"
  },
  {
    "name": "Letitia",
    "arcana": "Ghost",
    "cluster": null,
    "twin": null,
    "spoilBook": 4,
    "generation": 1,
    "origin": "Serena",
    "gender": "Dead Girl",
    "pronouns": "Was/Were",
    "created": 1992,
    "died": 1993,
    "age": null,
    "sphere": null
  },
  {
    "name": "Lolita Honey",
    "arcana": "Minor",
    "cluster": "Honeysuckle",
    "twin": "Loretta Alice",
    "spoilBook": 4,
    "generation": 1,
    "origin": "Letitia",
    "gender": "Cis Girl",
    "pronouns": "She/Her",
    "created": 1993,
    "died": null,
    "age": 12,
    "sphere": "Pyro Eshwelle"
  },
  {
    "name": "Loretta Alice",
    "arcana": "Minor",
    "cluster": "Honeysuckle",
    "twin": "Lolita Honey",
    "spoilBook": 4,
    "generation": 1,
    "origin": "Letitia",
    "gender": "Cis Girl",
    "pronouns": "She/Her",
    "created": 1993,
    "died": null,
    "age": 12,
    "sphere": "Pyro Eshwelle"
  },
  {
    "name": "Rose",
    "arcana": "Minor",
    "cluster": "Honeysuckle",
    "twin": "Katherine",
    "spoilBook": 1,
    "generation": 2,
    "origin": "Clairey",
    "gender": "Cis Woman",
    "pronouns": "She/Her",
    "created": 1994,
    "died": null,
    "age": 92,
    "sphere": "Opree Shengra"
  },
  {
    "name": "Katherine",
    "arcana": "Minor",
    "cluster": "Alicia",
    "twin": "Rose",
    "spoilBook": 1,
    "generation": 2,
    "origin": "Katie",
    "gender": "Cis Woman",
    "pronouns": "She/Her",
    "created": 1994,
    "died": null,
    "age": 92,
    "sphere": "Geren Eshper"
  },
  {
    "name": "Honeysuckle",
    "arcana": "Major",
    "cluster": "Honeysuckle",
    "twin": "Alicia",
    "spoilBook": 1,
    "generation": 2,
    "origin": "Lolita Honey",
    "gender": "Drag Princess",
    "pronouns": "(Ironic) She/Her",
    "created": 1995,
    "died": null,
    "age": 23,
    "sphere": "Opree Shengra"
  },
  {
    "name": "Alicia",
    "arcana": "Major",
    "cluster": "Alicia",
    "twin": "Honeysuckle",
    "spoilBook": 1,
    "generation": 2,
    "origin": "Loretta Alice",
    "gender": "Greygender",
    "pronouns": "She/Her",
    "created": 1995,
    "died": null,
    "age": 23,
    "sphere": "Pred Heres"
  },
  {
    "name": "Morgana",
    "arcana": "Major",
    "cluster": "Morgana",
    "twin": "Estella",
    "spoilBook": 1,
    "generation": 3,
    "origin": "Honeysuckle",
    "gender": "Cis Woman",
    "pronouns": "She/Her",
    "created": 1996,
    "died": null,
    "age": 41,
    "sphere": "Geren Eshper"
  },
  {
    "name": "Estella",
    "arcana": "Major",
    "cluster": "Estella",
    "twin": "Morgana",
    "spoilBook": 1,
    "generation": 3,
    "origin": "Alicia",
    "gender": "Drag Queen",
    "pronouns": "(Ironic) She/Her",
    "created": 1996,
    "died": null,
    "age": 41,
    "sphere": "Evol Espireth"
  },
  {
    "name": "Jane",
    "arcana": "Minor",
    "cluster": "Honeysuckle",
    "twin": "Kathy",
    "spoilBook": 1,
    "generation": 3,
    "origin": "Honeysuckle",
    "gender": "Cis Woman",
    "pronouns": "She/Her",
    "created": 1999,
    "died": null,
    "age": 40,
    "sphere": "Opree Shengra"
  },
  {
    "name": "Kathy",
    "arcana": "Minor",
    "cluster": "Alicia",
    "twin": "Jane",
    "spoilBook": 1,
    "generation": 3,
    "origin": "Alicia",
    "gender": "Cis Woman",
    "pronouns": "She/Her",
    "created": 1999,
    "died": null,
    "age": 40,
    "sphere": "Geren Eshper"
  },
  {
    "name": "Cal",
    "arcana": "Minor",
    "cluster": "Nooka",
    "twin": "Nooka",
    "spoilBook": 3,
    "generation": 4,
    "origin": "Mixed",
    "gender": "Trans Man",
    "pronouns": "He/Him",
    "created": 2005,
    "died": null,
    "age": 28,
    "sphere": "Godshi Enpire"
  },
  {
    "name": "Nooka",
    "arcana": "Major",
    "cluster": "Nooka",
    "twin": "Cal",
    "spoilBook": 5,
    "generation": 4,
    "origin": "Mixed",
    "gender": "Non-Binary",
    "pronouns": "They/Them",
    "created": 2005,
    "died": null,
    "age": 28,
    "sphere": "Bure Eshpel"
  },
  {
    "name": "Leandra",
    "arcana": "Minor",
    "cluster": "Honeysuckle",
    "twin": "Ash",
    "spoilBook": 3,
    "generation": 3,
    "origin": "Honeysuckle",
    "gender": "Cis Woman",
    "pronouns": "She/Her",
    "created": 2014,
    "died": null,
    "age": 26,
    "sphere": "Bure Eshpel"
  },
  {
    "name": "Ash",
    "arcana": "Minor",
    "cluster": "Alicia",
    "twin": "Leandra",
    "spoilBook": 3,
    "generation": 3,
    "origin": "Alicia",
    "gender": "Non-Binary",
    "pronouns": "He/Him",
    "created": 2014,
    "died": null,
    "age": 26,
    "sphere": "Pred Heres"
  },
  {
    "name": "Ava",
    "arcana": "Minor",
    "cluster": "Serena",
    "twin": "Tara",
    "spoilBook": 5,
    "generation": 1,
    "origin": "Serena",
    "gender": "Greygender",
    "pronouns": "She/Her",
    "created": 2014,
    "died": null,
    "age": 59,
    "sphere": "Opree Shengra"
  },
  {
    "name": "Tara",
    "arcana": "Minor",
    "cluster": "Serena",
    "twin": "Ava",
    "spoilBook": 5,
    "generation": 1,
    "origin": "Serena",
    "gender": "Cis Woman",
    "pronouns": "She/Her",
    "created": 2014,
    "died": null,
    "age": 59,
    "sphere": "Opree Shengra"
  }
]